### ISSUE TITLE
Need help resolving Arduino error

### ISSUE THREAD

**Issue by markdonofrio** [cifertech/nRF-jammer#2] opened 2022-10-25 14:01 UTC
I am using the ELEGOO NANO (ATmega328P & CH340 chip - I installed the latest drivers on it)

I tried to add the 2.4 GHz Band Scanner & Jammer With NRF24L01 code to the nano via Arduino and I am getting multiple errors.

Errors
——————
C:\Users\Gram\Desktop\Inventions\NRF Wifi Jam\RF_Box\RF_Box.ino:1:32: error: stray '#' in program
 <span style="font-size: 14px;">#include <SPI.h>
                                ^
C:\Users\Gram\Desktop\Inventions\NRF Wifi Jam\RF_Box\RF_Box.ino:1:1: error: expected unqualified-id before '<' token
 <span style="font-size: 14px;">#include <SPI.h>
 ^
In file included from C:\Users\Gram\Desktop\Inventions\NRF Wifi Jam\RF_Box\RF_Box.ino:3:0:
C:\Users\Gram\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.5\libraries\Wire\src/Wire.h:86:8: error: 'TwoWire' does not name a type; did you mean 'TwoWire_h'?
 extern TwoWire Wire;
        ^~~~~~~
        TwoWire_h
In file included from c:\Users\Gram\Documents\Arduino\libraries\Adafruit_GFX_Library/Adafruit_GFX.h:12:0,
                 from C:\Users\Gram\Desktop\Inventions\NRF Wifi Jam\RF_Box\RF_Box.ino:4:
c:\Users\Gram\Documents\Arduino\libraries\Adafruit_BusIO/Adafruit_I2CDevice.h:10:36: error: 'TwoWire' has not been declared
   Adafruit_I2CDevice(uint8_t addr, TwoWire *theWire = &Wire);
                                    ^~~~~~~
c:\Users\Gram\Documents\Arduino\libraries\Adafruit_BusIO/Adafruit_I2CDevice.h:30:3: error: 'TwoWire' does not name a type; did you mean 'TwoWire_h'?
   TwoWire *_wire;
   ^~~~~~~
   TwoWire_h
c:\Users\Gram\Documents\Arduino\libraries\Adafruit_BusIO/Adafruit_I2CDevice.h:10:56: error: 'Wire' was not declared in this scope
   Adafruit_I2CDevice(uint8_t addr, TwoWire *theWire = &Wire);
                                                        ^~~~
In file included from C:\Users\Gram\Desktop\Inventions\NRF Wifi Jam\RF_Box\RF_Box.ino:5:0:
c:\Users\Gram\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:132:42: error: 'TwoWire' has not been declared
   Adafruit_SSD1306(uint8_t w, uint8_t h, TwoWire *twi = &Wire,
                                          ^~~~~~~
c:\Users\Gram\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:175:3: error: 'TwoWire' does not name a type; did you mean 'TwoWire_h'?
   TwoWire *wire;   ///< Initialized during construction when using I2C. See
   ^~~~~~~
   TwoWire_h
c:\Users\Gram\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:132:58: error: 'Wire' was not declared in this scope
   Adafruit_SSD1306(uint8_t w, uint8_t h, TwoWire *twi = &Wire,
                                                          ^~~~
C:\Users\Gram\Desktop\Inventions\NRF Wifi Jam\RF_Box\RF_Box.ino:23:55: error: 'Wire' was not declared in this scope
 Adafruit_SSD1306 display = Adafruit_SSD1306(128, 32, &Wire);
                                                       ^~~~
C:\Users\Gram\Desktop\Inventions\NRF Wifi Jam\RF_Box\RF_Box.ino:23:55: note: suggested alternative: 'line'
 Adafruit_SSD1306 display = Adafruit_SSD1306(128, 32, &Wire);
                                                       ^~~~
                                                       line
C:\Users\Gram\Desktop\Inventions\NRF Wifi Jam\RF_Box\RF_Box.ino:270:1: error: expected unqualified-id before '<' token
 </span>
 ^

exit status 1

Compilation error: stray '#' in program

**Comment by markdonofrio** [comment] 2022-10-25 14:35
I also tried to download the previous version of Arduino 1.8.12 and i got the download complete for the RF_Box and still it is not working.

![image](https://user-images.githubusercontent.com/15877411/197803065-c7128c28-9535-4447-819b-f15280d26fcc.png)

**Comment by markdonofrio** [comment] 2022-10-25 14:40
Connections

![image](https://user-images.githubusercontent.com/15877411/197804254-2c131a17-c63b-48a1-8660-dbac258662a6.png)

**Comment by cifertech** [comment] 2022-10-28 17:03
Hi @markdonofrio . the new display is fine and for code/schematic everything in the related repository is could be trusted to work with.
as I test these codes with no problem it might be a problem with your Arduino libraries which are installed before.
I recommend that clear your Arduino library folder and install the needed one again or simply use another computer.
because codes are fine and the issue is in your software. As far as I know.

**Comment by markdonofrio** [comment] 2022-11-01 14:21
I deleted all libraries.  Installed the latest Arduino IDE + latest ADAFRUIT, GFX & IO libraries (they were identified as a group automatically so I clicked download all button).  I restarted Arduino.  When I try and verify the RF_Box code i get the following error.
------------------------------------------

C:\Users\Gram\Desktop\Inventions\NRF Wifi Jam\nRF-jammer-main\nRF-jammer-main\RF_Box\RF_Box.ino:7:10: fatal error: RF24.h: No such file or directory
 #include <RF24.h>
          ^~~~~~~~
compilation terminated.

exit status 1

Compilation error: RF24.h: No such file or directory

**Comment by markdonofrio** [comment] 2022-11-01 14:28
I installed RF24 library latest and now it says the sketch installed successfully but the device has not started working as suggested above.
----------------------------------------
Sketch uses 18460 bytes (60%) of program storage space. Maximum is 30720 bytes.
Global variables use 993 bytes (48%) of dynamic memory, leaving 1055 bytes for local variables. Maximum is 2048 bytes.

**Comment by markdonofrio** [comment] 2022-11-01 18:25
![image](https://user-images.githubusercontent.com/15877411/199309619-acc0a8f3-ad4b-4f03-9e0f-cd52c047bda5.jpeg)

**Comment by markdonofrio** [comment] 2022-11-01 18:43
I reset the nano chip by unplugging it now the TX light is solid

https://user-images.githubusercontent.com/15877411/199312829-ba15db27-493c-46be-a772-29932cc72c7e.MOV

**Comment by cifertech** [comment] 2022-11-03 10:43
Hi @markdonofrio , i tested the code. its working correctly. it might be your connections.

Connect sda to A4 and sck to A5.

![20221103_140916.jpg](https://user-images.githubusercontent.com/62047147/199700986-157555d7-f1d2-4d23-8cc4-5c565b7d8839.jpg)

**Comment by markdonofrio** [comment] 2022-11-03 10:53
My LCD has SCL and SDA ports.  Which connections should I make?

**Comment by cifertech** [comment] 2022-11-03 11:09
They are same. (SCK / SCL)

**Comment by cifertech** [comment] 2022-11-03 11:11
AS THE CODE AND DOCUMENTATION ARE OK AND THERE IS NO PROBLEM I CLOSE THIS ISSUE. FEEL FREE TO OPEN IT IF YOU FIND A PROBLEM IN THE CODE FOR DOCUMENTATION.

**Closed by cifertech** 2022-11-03 11:11 UTC
